name: New Project Proposal
description: Template for proposing a new project to the TAC
title: 'New Project Proposal - PROJECT NAME'
assignees: 
  - Ulrick28
  - Naomi-Wash
body:
- type: markdown
  attributes:
    value: |
      Thank you for looking to bring your project to the Open 3D Foundation.
      Please put the project's name in the title above, replacing PROJECT NAME,
      and then answer the questions below to have this project proposal added
      to the agenda at a future TAC meeting for consideration as a new project. 
      Please refer to the guidance in the Project Lifecycle. 
      Please also note you must be available to lead this discussion at a TAC meeting.
- type: textarea
  id: project-description
  attributes:
    label: Project Description
    description: "Please describe the purpose and function of the project, its origin, and its
    significance to the ecosystem"
  validations:
    required: true
- type: dropdown
  id: project-stage
  attributes:
    label: Proposed Project Stage
    options:
      - Incubation
      - Growth
      - Impact
      - Emeritus
  validations:
    required: true
- type: textarea
  id: project-alignment
  attributes:
    label: Project Alignment
    description: "Please explain how this project is aligned with the mission of the Open 3D Foundation?
    https://o3df.org/about/overview/"
  validations:
    required: true
- type: textarea
  id: code-of-conduct
  attributes:
    label: Code of Conduct
    description: "Provide a link to current Code of Conduct if one is adopted already"
  validations:
    required: true
- type: textarea
  id: tac-sponsor
  attributes:
    label: Sponsor from TAC
    description: Sponsor helps mentor projects - if the project doesn't currently have a sponsor, the TAC will appoint one as part of the approval process
  validations:
    required: true
- type: textarea
  id: license-and-contribution-guidelines
  attributes:
    label: What is the project’s license for code contributions and methodology for code contributions?
    description: "O3DF maintains recommendations for contribution and licensing for hosted projects."
  validations:
    required: true
- type: textarea
  id: source-control
  attributes:
    label: What tool or platform is utilized for source control (GitHub, etc.), and what is the location (e.g., URL)?
  validations:
    required: true
- type: textarea
  id: external-dependencies
  attributes:
    label: What are the external dependencies of the project, and what are the licenses of those dependencies?
  validations:
    required: true
- type: textarea
  id: issue-tracker
  attributes:
    label: What tool or platform is leveraged by the project for issue tracking?
  validations:
    required: true
- type: textarea
  id: release-methodology
  attributes:
    label: What is the project’s release methodology and cadence?
  validations:
    required: true
- type: textarea
  id: project-roles-and-leadership
  attributes:
    label: What leadership and roles does the project have?
    description: Describe the project's leadership team and decision-making process. What roles does the project have (e.g. maintainers, committers)? Who are the current core committers of the project or where can a list of committers be found?
  validations:
    required: true
- type: textarea
  id: governance
  attributes:
    label: Link to any documented governance practices 
- type: textarea
  id: financial-sponsorship
  attributes:
    label: Are there existing financial sponsorships?
  validations:
    required: true
- type: textarea
  id: infrastructure
  attributes:
    label: Detail the infrastructure needs or requests
  validations:
    required: true
- type: textarea
  id: openssf-best-practices-badge
  attributes:
    label: Does the project have an OpenSSF Best Practices Badge? Do you foresee any challenges in obtaining one?
    description: Read more about the OpenSSF Best Practices Badge at https://bestpractices.coreinfrastucture.org
  validations:
    required: true
- type: textarea
  id: communication-channels
  attributes:
    label: What are the project's official communication channels?
    description: List of the project's official communication channels (mailing lists, slack, discord, irc)
  validations:
    required: true
- type: textarea
  id: website
  attributes:
    label: What is the project’s website? Is there a wiki?
  validations:
    required: true
- type: textarea
  id: social-media
  attributes:
    label: What social media accounts are used by the project?
  validations:
    required: true
- type: textarea
  id: trademarks
  attributes:
    label: Are any trademarks, registered or unregistered, leveraged by the project? Have any trademark registrations been filed by the project or any third party anywhere in the world?
  validations:
    required: true
