name: New Project Proposal
description: Template for proposing a new project to the TAC
title: 'New Project Proposal - PROJECT NAME'
assignees: 
  - Ulrick28
  - Naomi-Wash
body:
- type: markdown
  attributes:
    value: |
      Thank you for looking to bring your project to the Open 3D Foundation.
      Please put the project's name in the title above, replacing PROJECT NAME,
      and then answer the questions below to have this project proposal added
      to the agenda at a future TAC meeting for consideration as a new project. 
      Please refer to the guidance in the Project Lifecycle. 
      Please also note you must be available to lead this discussion at a TAC meeting.
- type: textarea
  id: project-name
  attributes:
    label: Project Name
    description: "Please provide the project name"
  validations:
    required: true
- type: textarea
  id: project-description
  attributes:
    label: Project Description
    description: "Please describe the purpose and function of the project, its origin, and its
    significance to the ecosystem"
  validations:
    required: true
- type: dropdown
  id: project-stage
  attributes:
    label: Proposed Project Stage
    options:
      - Incubation
      - Growth
      - Impact
      - Emeritus
  validations:
    required: true
- type: textarea
  id: project-alignment
  attributes:
    label: Project Alignment
    description: "Please explain how this project is aligned with the mission of the Open 3D Foundation?
    https://o3df.org/about/overview/"
  validations:
    required: true
- type: textarea
  id: code-of-conduct
  attributes:
    label: Code of Conduct
    description: "Provide a link to current Code of Conduct if one is adopted already"
  validations:
    required: true

    
